x = set(["apple", "mango"])
y = set(["mango", "orange"])
z = set(["mango"])
a = set(["apple"])
b = set(["orange", "orange"])
print(x.issubset(y))
print(y.issubset(x))
print(x.issubset(z))
print(z.issubset(y))
print(a.issubset(x))
print(b.issubset(y))